# 1

## 1.1 Getting started

Here's a list of employees, pay rate, and hours worked

```{bash}
cat emp.data
```


Calculating pay for people who worked > 0 hours

```{bash}
mawk '$3 > 0 {print $1, $2*$3}' emp.data
```

The people who didn't work

```{bash}
mawk '$3 == 0 {print $1}' emp.data
```


As you may be able to see from the above two examples, most of the awk programs we'll be writing have a certain set up: `pattern {action}`, where we have a pattern that we match (e.g., the 3rd field is `0`) and then an action based on those rows that match the pattern.




















## 1.2 Simple output

In the first code chunk, I wrote `cat emp.data`. The awk equivalent is

```{bash}
mawk '{print}' emp.data
```

`print $0` will also print the whole line


```{bash}
mawk '{print $0}' emp.data
```

Now without the pay rate

```{bash}
mawk '{print $1, $3}' emp.data
```

Note that comma between field 1 and 3 is semirequired. See the output without the comma.

```{bash}
mawk '{print NF, $1, $NF}' emp.data
```

`NF` counts the number of fields for every line, which yields a 3 to start every column. 

Another built in variable is `NR`

```{bash}
mawk '{print NR, $1}' emp.data
```

This, paired with `$1` outputs the line number with every name. You can also adjust the output by adding text

```{bash}
mawk '{print "The total pay for", $1, "is", $2 * $3}' emp.data
```























## 1.3 Fanicer output

This printing can be made fanicer by using `printf`

```{bash}
mawk '{printf "The total pay for %-5s is $%6.2f \n", $1, $2 * $3}' emp.data
```

If you have any experience with C's `printf` (and many other similar `printf`s), you can do the same here with awk. Adjust the justification, number of digits before and after the decimal, etc.



Awk doesn't need to be used in isolation. If you want to use `sort` pipe it to `sort`

```{bash}
mawk '{printf "$%6.2f %s\n", $2 * $3, $1}' emp.data | sort
```

















## 1.4 Selection


The people that worked 20 or more hours

```{bash}
mawk '$3 >= 20' emp.data 
```

The people that were paid more than $50

```{bash}
mawk '$2 * $3 > 50 {printf "%s made more than $50: $%-6.2f\n", $1, $2 * $3}' emp.data | sort
```


You can do more than just select based on numbers. Here's characters

```{bash}
mawk '$1 == "Mark"' emp.data 
```

and using regular expressions

```{bash}
mawk '/Ma/' emp.data
```

`||` is *or* `&&` is *and*

```{bash}
mawk '/Ma/ || /th/' emp.data
```

```{bash}
mawk '/Ma/ && $3 > 21' emp.data
```

You can also use these for data validation. E.g., you can't be paid negative dollars, work negative hours, or have more fields than 3 (in this case). Here's that implemented in awk

```{bash}
mawk 'NF != 3 || $2 < 0 || $3 < 0' emp.data
```

Since there's no errors, there's no output. To make sure this is the case. I'll make `emp_error.data`.

```{bash}
mawk 'NF != 3 || $2 < 0 || $3 < 0' emp_error.data
```


In addition to `NF` and `NR`, there's `BEGIN` and `END`

```{bash}
mawk 'BEGIN {print "NAME RATE HOURS"}{print}' emp.data
```























## 1.5 Computing with awk

Here's how to count the number of people who worked. Remember it should be 4.

```{bash}
mawk '$3 > 0' emp.data
```

```{bash}
mawk '$3 > 0 {emp += 1} END {print emp}' emp.data
```

Or, what fraction of the total employees worked more than 0 hours?

```{bash}
mawk '$3 > 0 {emp += 1} END {print emp / NR}' emp.data
```

Using these ideas, you can easily print the total amount paid out to the people in `emp.data`, the average pay, and the total and average number of hours worked.

```{bash}
mawk '{pay = pay + $2 * $3; hours = hours + $3} END {
printf "the total pay is %.2f\n\
the average pay is %.2f\n\
the total number of hours is %.2f\n\
the average number of hours is %.2f\n",
pay, pay/NR, hours, hours/NR}' emp.data
```

Here's how to find and print the highest rate

```{bash}
mawk '$2 > maxrate {maxrate = $2; maxemp = $1} END {
print "highest hourly rate:", maxrate, "for", maxemp}' emp.data
```

and hours

```{bash}
mawk '$3 > maxhours {maxhours = $3; maxemp = $1} END {
print "highest hours:", maxhours, "for", maxemp}' emp.data
```

You can concatenate the values in columns

```{bash}
mawk '{names = names $1 " "} END {print names}' emp.data
mawk '{names = names $1 "\n"} END {print names}' emp.data
```

```{bash}
mawk '{names = names $2 " "} END {print names}' emp.data
mawk '{names = names $2 "\n"} END {print names}' emp.data
```

Print the last column of the last line like so

```{bash}
mawk 'END {print $NF}' emp.data
```

Or the whole last line

```{bash}
mawk '{last = $0} END {print last}' emp.data
```

or simply do this

```{bash}
mawk 'END {print $0}' emp.data
```


Or the 3rd line

```{bash}
mawk 'NR == 3 {print $0}' emp.data
```



Other built-in functions include `length`

```{bash}
mawk '{print $1, length($1)}' emp.data
```

which is the length of the string in each row in column 1 (names).


```{bash}
mawk '/Ma/{print length($1)}' emp.data
```

Both of the Ma-containing names are of length 4.


```{bash}
mawk '{l = l + length($1)} END {print l / NR}' emp.data
```

The average name length is 4.16667 (which is 25 / 6).













## 1.6 Control-flow statements

Relatively straightforward `if else`

```{bash}
mawk '$2 > 4 {num = num + 1; pay = pay + $2 * $3} END {if (num > 0)
    print num, "employees\ntotal pay is", pay,
    "\naverage pay is", pay/num
    else
    print "no employees are paid more than $4 per hour"}' emp.data
```

```{bash}
mawk '$2 > 5.5 {num = num + 1; pay = pay + $2 * $3} END {if (num > 0)        # 5.5
    print num, "employees\ntotal pay is", pay,
    "\naverage pay is", pay/num
    else
    print "no employees are paid more than $5.5 per hour"}' emp.data
```



Here's the ternary operator in awk: `condition ? statement1 : statement2` 

```{bash}
mawk '{pay = $2 * $3 }{print $1, pay} END {print " "}' emp.data
mawk '{print ($2 * $3) < 50 ? "low" : "high"}' emp.data
```



Next, the For statement:

```{bash, eval=FALSE}
mawk 'BEGIN {
  for(i = 1; i <= 10; i++)
    print i
}'
```



As a more useful example, put this code in `interest.awk`

```{bash, eval=FALSE}
# interest2 - compute compound interest
# input: amount rate years
# output: compounded value at the end of each year
{
  printf("\t%.2f\n", $1)
  for (i = 1; i <= $3; i++)
    printf("\t%.2f\n", $1 * (1 + $2) ^ i)
}
```

Then run with an `echo`d input

```{bash}
echo "60000 0.025 10" | mawk -f interest.awk
```









## 1.7 Arrays


```{bash}
# reverse - print input in reverse order by line
mawk '{
line[NR] = $0} END {
  for(i = NR; i > 0; i--)
    print line[i]
    }' emp.data

```

```{bash}
mawk '{
line[NR] = $3} END {
    print line[4], line[5], line[4] * line[5]
    }' emp.data
```









## 1.8 A Handful of Useful "One-liners"


Number of lines

```{bash}
mawk 'END {print NR}' emp.data
```




Print last row

```{bash}
mawk '{print $NR}' emp.data
```



Print largest value of the second column and the line that contains it

```{bash}
mawk '{print $0}' emp.data
```


```{bash}
mawk '$2>max {max = $2; maxline = $0} END {print max, maxline}' emp.data
```


Print every line after erasing the 3rd field 

```{bash}
mawk '{$3 = ""; print}' emp.data
```





```{bash}
mawk '/a/ {nlines = nlines + 1} END {print nlines}' emp.data
mawk '/a/ || /t/ {nlines = nlines + 1} END {print nlines}' emp.data
```







## 1.9 What next?






